### ISSUE TITLE
[JUnit5] Introduce injection mechanism for comonly used resources

### ISSUE THREAD

**Issue by istraka** [wildfly-extras/sunstone#110]
**What to inject**
What need to be injected:
- `Hostname` for:
  - Azure VM
  - EC2 instance
  - Azure Web application (app service)
- `Ec2Client` logged & ready to use
- `S3Client` logged & ready to use
- `AzureResourceManager` logged & ready to use
- `OnlineManagementClient` logged & ready to use for:
  - EC2 instance
  - Azure VM

**How to inject**
One annotation shall be used for injection of all types: `@SunstoneResource`

**When is injection done**
Injection should happen for both static and non-static field. 
- Static field shall be injected once per test-class in `BeforeAllCallback` once all deployments are deployed and configured.
- Non-static field shall be injected per test instance (per test method) in `postProcessTestInstance` phase.

**Resource identification**
Type of field determines what the type of resource that should be injected, e.g. `S3Client`, `OnlineManagementClient`, ... types. If there is an ambiguity - i.e. `Hostname` is basically a `String` which however can not be used for determining that the user wants to inject in fact the hostname - then new interface shall be introduced, which in this particular case is a `Hostname` interface with one method `get()`.

To determine resource, a mechanism to identify deployed resource must be present. I.e. an user want to inject `Hostname` then he needs to provide identification of the resource so that Sunstone can get its the hostname. A resource should be identified by its name, for example for Azure VMs it is a name. For AWS EC2 instance it is a `nameTag`. Then a kind of a hint must be present because:
- in AWS resource may have same name and it can not be determined whether an user want to inject hostname of a loadbalancer or EC2 instance
- performance - Sunstone should not list all possible kinds of resources 

**What could it look like?**

```
@SunstoneResource(resource = "resourceName", hint = Hint.AWS_EC2_INSTANCE)
Hostname hostname;
```
**pros**:
- IDE can help with hint that is an enum

**cons**:
- kind of long
- two parameters / identifiers

```
@SunstoneResource("AWS::EC2Instance/resourceName")
Hostname hostname;
```
**pros**:
- looks better (subjective)
- shorter & just one parameter
- it scales better, i.e in the future I can have `AWS::region/east-us1` for injecting client when I use multiple regions (when clients are created, region must be specified)

**cons**:
- IDE won't help you

WDYT @LittleJohnII @tommaso-borgato @mnovak1

**Comment by mnovak1** [comment]
I think the 1st way is better (at least for me :-) ). I prefer when IDE can help me instead of looking for and trying "magic" strings.

**Comment by istraka** [comment]
Another thing is documentation. Let's say I want to inject `OnlineManagementClient`. First I need to find that `OnlineManagementClient` is in fact injectable, then I need to get information that it works for my type of resource - `hint` parameter and then I need to find what should I put into `resource` parameter.

For the second case JavaDoc shall look like:
- `OnlineManagementClient`: 
  - for EC2 use AWS::EC2Instance/<value of tagName>`
  - for AZ VM use `AZ::VM/<instance name>`
  
IMO finding out how to set two parameters is more complicated than one parameters. It is also more complicated to document it properly so that test development is easy.

**Comment by istraka** [comment]
If there are no other suggestion I will go with the second options mainly due to scalability. We don't know which all types we will need a support for the injection and therefore their identification is unknown. It is easier to extend the definition of said string than to add more parameters.

**Comment by istraka** [comment]
After internal discussion on google chat we have determined to go another way and to have specific annotation for specific cloud resources as having only one String still doesn't scale properly.

**Comment by istraka** [comment]
Fixed by:
https://github.com/wildfly-extras/sunstone/pull/119
https://github.com/wildfly-extras/sunstone/pull/117
