### ISSUE TITLE
WildFlyNode - add possibility to kill WildFly/EAP process

### ISSUE THREAD

**Issue by kwart** [wildfly-extras/sunstone#12]
Internal ID: 15

Add a new method `killWildFly()` which finds and kills WFLY/EAP java processes.

**Comment by kwart** [comment]
You can get the pid by calling via CLI `/core-service=platform-mbean/type=runtime:read-attribute(name=name)` and the part before `@` is the pid. In case of domain you can get the pid for each host controller by using `/host=@HOST_CONTROLLER_NAME@/core-service=platform-mbean/type=runtime:read-attribute(name=name)`.

That is basically equivalent of the JMX-based workaround for getting current PID inside a Java process that you can find everywhere on the web.

**Comment by istraka** [comment]
This is a feature for 1.x branch, which is in a maintenance mode.
