### ISSUE TITLE
OpenShift cloud provider

### ISSUE THREAD

**Issue by kwart** [wildfly-extras/sunstone#17]
Internal ID: 32

Does it make sense? v2 and/or v3? Relationship to the Kubernetes provider (#16)?

**Comment by LittleJohnII** [comment]
I'm currently looking into basing this provider on top of https://github.com/openshift/openshift-restclient-java. An alternative might be https://github.com/fabric8io/kubernetes-client, which I haven't looked into yet.

**Comment by LittleJohnII** [comment]
WIP on branch https://github.com/LittleJohnII/sunstone/tree/issue-16

**Comment by istraka** [comment]
This is a feature for 1.x branch, which is in a maintenance mode.
