### ISSUE TITLE
SunstoneProperty not expanding values

### ISSUE THREAD

**Issue by laDok8** [wildfly-extras/sunstone#187]
Sunstone property injection defaults to null when manipulated with eg. [SunstonePropertyTest](https://github.com/wildfly-extras/sunstone/blob/main/core/src/test/java/sunstone/core/di/SunstonePropertyTest.java) 
doesn't work with this test added
```

    String appendedExpression = expression + "+appended";
    
   @Test
    public void appendedExpressionTest() {
        Assertions.assertThat(appendedExpression).isEqualTo("expressionDefaultValue+appended");
```

**Comment by istraka** [comment]
`@SunstoneProperty` consumes property name, it does not resolve expression.
