### ISSUE TITLE
EC2Node can return from constructor before the instance is in running state

### ISSUE THREAD

**Issue by kwart** [wildfly-extras/sunstone#19]
Internal ID: 46

This means that with a nice user-data script, you can get an instance that's not yet prepared for use. We do wait for ports to open, but the instance startup can be longer than that. We should wait for AWS to register the instance as running.

**Comment by istraka** [comment]
This is an enhancement. If a user define long running user data script, he should also adjust timeouts. 

This is for 1.x branch which is in a maintenance mode.
