### ISSUE TITLE
node configuration doesn't have a link to cloud provider configuration

### ISSUE THREAD

**Issue by kwart** [wildfly-extras/sunstone#23]
Internal ID: 58

This was probably intentional, but it's not very convenient. I don't think people will be writing node configuration in such a way that they could start the node in multiple cloud providers (though they theoretically can). At the same time, the link would be useful -- e.g. for the bare metal provider (actually for the byon JClouds provider) or for the Arquillian extension.

Are we gonna do something about that?

**Comment by kwart** [comment]
This is intentional. IMHO we should have that documented, because it's not very intuitive.

**Comment by Ladicek** [comment]
Once I understood what the original intention was, I think this issue should be closed. Having it documented would be good, preferrably with a description of how it helps us.

**Comment by kwart** [comment]
Closing. If we'll realize in future we need the node-to-provider configuration link in other cases than arquillian, we can reopen this.
