### ISSUE TITLE
Leaking provisioned virtual machines if an exception is thrown in waitForStartPorts()

### ISSUE THREAD

**Issue by kwart** [wildfly-extras/sunstone#24]
Internal ID: 75

From `AzureNode` (but this is the case in other Nodes as well):
```java
        try {
            this.initialNodeMetadata = createNode(template);
            String publicAddress = Iterables.getFirst(initialNodeMetadata.getPublicAddresses(), null);
            LOGGER.info("Started {} node '{}' from image {}, its public IP address is {}",
                    cloudProvider.getCloudProviderType().getHumanReadableName(), name, imageName, publicAddress);
            waitForStartPorts();
        } catch (RunNodesException e) {
            throw new RuntimeException("Unable to create " + cloudProvider.getCloudProviderType().getHumanReadableName()
                    + " node from template " + template, e);
        }
```
If an exception is thrown in `waitForStartPorts` it is a subclass of RuntimeException and isn't caught. In this case, the VM has already been successfully provisioned and it is not destroyed when the exception is thrown.

**Comment by kwart** [comment]
@Ladicek commented: The first part is moving the `waitForStartPorts` outside of the original `try` block, which is meant for starting the node, and the second part is adding a dedicated `try` block that needs to close the started node in case of an exception.

I think that fixing this issue could be done together with unifying the after-boot script execution, if enough time.

**Comment by LittleJohnII** [comment]
I believe this has been resolved by https://github.com/wildfly-extras/sunstone/pull/30. Let's close this, unless there's some more work to do.

**Comment by Ladicek** [comment]
+1

**Comment by kwart** [comment]
Yep, you're right. I didn't realize it's not closed automagically.
