### ISSUE TITLE
Node group too long for EC2

### ISSUE THREAD

**Issue by kwart** [wildfly-extras/sunstone#27]
Internal ID: 89

The node group name can be too long for EC2. The limitation is 63 characters.

```
Object 'cloudts-jenkins-eap-7x-amazon-domain-simple-cluster-test-rhel6-1' doesn't match dns naming constraints. Reason: Can't be null or empty. Length must be 3 to 63 symbols.
```

**Comment by LittleJohnII** [comment]
Update - the issue isn't with EC2 limiting the length, it's JClouds that place the limitation. Nevertheless, it's easily resolvable.

**Comment by LittleJohnII** [comment]
Update - Ignasi suggests that the limit should be made configurable instead of removing it. In that case, we could set the limit arbitrarily high when creating the  EC2CloudProvider. I'll have a look at it and possibly create a PR.
