### ISSUE TITLE
WildFly Node should be able to create management user automaticaly

### ISSUE THREAD

**Issue by kwart** [wildfly-extras/sunstone#28]
When using creaper from WildFly node, it uses auth version which expects to have properly defined user on EAP. This user creation should be created automatically to simplify usage.

User doesn't want to need to track how it is defined across different images when it can be handled automatically. There is no issue in having defined multiple management users on EAP/WildFly server => there can be added one by the sunstone library automatically for usage by creaper.

**Comment by kwart** [comment]
@Ladicek commented:

> That kinda sorta makes sense, but it also doesn't. If anything, I'd expect this to be strictly opt-in.

**Comment by istraka** [comment]
This is for branch 1.x which is in a maintenance mode.
