### ISSUE TITLE
Add protection to temporary content

### ISSUE THREAD

**Issue by kwart** [wildfly-extras/sunstone#3]
The `README.md` says,

> Some properties are expected to contain file paths. This is typical e.g. for SSH private keys:
>
> node.nodeA.openstack.ssh.privateKeyFile=/home/me/.ssh/id_rsa
>
> In such cases, it is possible to load data also from classpath, using the classpath: prefix:
>
> node.nodeA.openstack.ssh.privateKeyFile=classpath:org/jboss/test/openstack/ssh-private-key.pem
>
> Note that these classpath resources are actually copied to the filesystem and the resulting temporary files are scheduled to be deleted at JVM exit. This shouldn't be a concern typically.

Doing "node.nodeA.openstack.ssh.privateKeyFile=classpath:test/ssh-private-key.pem" will expose
the temporary copy of the private key to local users on the system for a while. 

We should add some level of protection here.

**Comment by Ladicek** [comment]
I was thinking about this for a while when I wrote the classpath reading code, but didn't come with anything satisfactory :-(

**Comment by kwart** [comment]
IMO, the `File` methods should be sufficient. Let's steal it e.g. from here:

https://github.com/wildfly/wildfly-core/blob/3.0.0.Alpha5/controller/src/main/java/org/jboss/as/controller/audit/AbstractFileAuditLogHandler.java#L182-L195

**Comment by Ladicek** [comment]
Aha, this! Yea, that would be at least something.

I was more thinking about reading the classpath resource into memory and serving it from there, but JClouds don't have a general API for that (or I didn't find one).
