### ISSUE TITLE
Investigate use of JSON configuration files

### ISSUE THREAD

**Issue by LittleJohnII** [wildfly-extras/sunstone#31]
It has been suggested that we investigate the use of structured configuration files - using JSON instead of .properties. Libraries for working with JSON (Jackson/GSON/...) could allow us to construct configuration objects directly from the configuration files.

Cc @jmartisk

**Comment by Ladicek** [comment]
I personally consider JSON human-nonreadable and nonwriteable. If you want something more structured, YAML would be an obvious suggestion, but frankly, I think properties work fairly well for Sunstone purposes.

**Comment by istraka** [comment]
This is for 1.x branch which is in a maintenance mode.
