### ISSUE TITLE
Expose configuration for private IP address in baremetal provider

### ISSUE THREAD

**Issue by rhatlapa** [wildfly-extras/sunstone#39]
When using baremetal provider, there should be option to configure also its private IP addresses as you might want to have defined some virtual network between nodes in the clouds and want to be able to access these addresses also when using bare provider. Or you just want to mimic with the baremetal provider the same public vs private IP address setup as when using some other cloud provider where public and private IP addresses are not equal.

**Comment by Ladicek** [comment]
https://github.com/wildfly-extras/sunstone/blob/5a3e8b8b/core/src/main/java/org/wildfly/extras/sunstone/api/impl/baremetal/BareMetalNode.java#L66
