### ISSUE TITLE
Run BaremetalTest against a Docker container

### ISSUE THREAD

**Issue by kwart** [wildfly-extras/sunstone#42]
As the Sunstone tests expect to Docker provider to be configured, we can reuse it also for BaremetalCloudProvider testing. Currently the BaremetalTest expects an SSH-able host and the test run must be allowed by system property `-Dbaremetal.run`.

**Comment by Ladicek** [comment]
I certainly don't think that "Sunstone tests expect to Docker provider to be configured" is true in general. Each test has its own expectations. The bare metal test could certainly expect that the Docker provider is configured, though :-)

It's a good idea, actually. Wonder why I didn't think of that myself...
