### ISSUE TITLE
SSH requires NOPASSWD sudo permissions from user

### ISSUE THREAD

**Issue by dudaerich** [wildfly-extras/sunstone#59]
In JCloudsSshClient, there is a code

```
ExecResponse sudoersResult = jcloudsSshClient.exec("sh -c '" + SshUtils.FileType.getShellTestStr("/etc/sudoers") + "'");
SshUtils.FileType sudoersFile = SshUtils.FileType.fromExitCode(sudoersResult.getExitStatus());
if (sudoersFile == SshUtils.FileType.FILE) {
     // see https://bugzilla.redhat.com/show_bug.cgi?id=1020147
     LOGGER.trace("Removing 'Defaults requiretty' from /etc/sudoers so that sudo works without a PTY");
     ExecResponse result = jcloudsSshClient.exec("sudo sed -i -e 's/Defaults    requiretty/#Defaults    requiretty/' /etc/sudoers");
     if (result.getExitStatus() != 0) {
           LOGGER.warn("Failed removing 'Defaults requiretty' from /etc/sudoers, running with sudo might not work");
           LOGGER.debug("stdout: {}", result.getOutput());
           LOGGER.debug("stderr: {}", result.getError());
      }
}
```

This code requires that the user must have sudo permissions which can be used without password. If normal user tries to connect via SSH, the `sudo sed...` command hangs for 5 minutes, because sudo asks a password.

I understand why this is needed, but maybe we should consider to move this "hack" somewhere else. Would be possible to remove the line in /etc/sudoers in bootScript?

**Comment by kwart** [comment]
I agree, we must have possibility to disable this. Or rather a possibility to use this fix only when a property is set.

Other improvement here would be using `-n` (`--non-interactive`) sudo argument to fail-fast.
